### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by mcollina** [andreareginato/conference_site#12]
Why don't we put a simple form to signup on a mailchimp-controlled list?
So we can push out updates.

**Comment by andreaforni** [comment]
+1 Great idea

**Comment by mcollina** [comment]
Ideally we might want to use this API:
http://apidocs.mailchimp.com/api/how-to/basic-subscribe.php

2012/1/26 Andrea Forni <
reply@reply.github.com

**Comment by mcollina** [comment]
Here it is the form for the website, as provided by mailchimp.
Obiouvsly you should remove all the classes and the divs, and style it like everything else in the site!

```
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="http://rubyday.us4.list-manage.com/subscribe/post?u=c9c6cfcde0d5ae20f60be2174&amp;id=d8e33dce43" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
    <h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
    <div id="mce-responses" class="clear">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
    </div>  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->
```

**Comment by andreaforni** [comment]
Hi guys,
this evening I've created a personal account on MailChimp and I've tried to do some tests to find the better way to integrate this service in the web site. 

The simplest way to do that is copy&paste an HTML snippet with a FORM generated by MailChimp. The downside of this choice is that the user is redirected to a MailChimp page after submitting the form. We can customize this page, but the user experience in not the best, the user does not remain on the RubyDay's website.

A better solution is to try to use the API provided by MailChimp. I read the link posted by Matteo: http://apidocs.mailchimp.com/api/how-to/basic-subscribe.php

The first big problem is that we don't have a back-end, so we cannot use the API to dialogue  with the service.

We can use a HTML query string (http://apidocs.mailchimp.com/api/how-to/#ex3) but if we put it in a FORM, the submission will redirect the user to a page with the data returned by the server (usually a JSON data structure).

So, I decided to use AJAX. I intercept the click event on the form's submit button and I build a AJAX request with JQuery which does the real dialogue with the service. Unfortunately I get the following error:

> XMLHttpRequest cannot load http://us4.api.mailchimp.com/1.3/. Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.

We cannot send an AJAX request to a domain which is different from the one of the website.

These last two methods are, in some way, wrong because they expose the API-key to all the users but, as you can read in this page http://kb.mailchimp.com/article/keeping-your-api-key-secure , the API-key must be kept private.

This is what I've done this evening, maybe I'm missing something but I don't see many options. I think that the only one available is the first one: using the FORM generated by MailChimp.

bye,
Andrea

**Comment by mcollina** [comment]
I think that's the simplest one, and it's really easy to implent.
Just find a way to integrate that form graphically and we will be ok for
the CFP.

**Comment by mcollina** [comment]
Fixed.
